import { DiaryEntry, TaskItem, FinanceRecord, DailyAlarm } from '../types';

export const initialAlarms: DailyAlarm[] = [
  {
    id: 'alarm-1',
    title: 'Pengingat Refleksi Pagi & Perencanaan Hari',
    time: '07:00',
    enabled: true,
    days: [1, 2, 3, 4, 5],
    sound: 'zen-bell',
  },
  {
    id: 'alarm-2',
    title: 'Evaluasi Tugas & Catat Pengeluaran Harian',
    time: '20:30',
    enabled: true,
    days: [0, 1, 2, 3, 4, 5, 6],
    sound: 'marimba',
  },
];

export const initialDiaryEntries: DiaryEntry[] = [
  {
    id: 'diary-1',
    title: 'Pagi yang tenang dan secangkir kopi hangat',
    content:
      'Hari ini bangun lebih awal dari biasanya. Suasana kota masih sangat sepi dan udara terasa sejuk. Menyeduh kopi manual sambil mendengarkan suara burung di halaman belakang. Rasanya damai sekali bisa duduk sejenak tanpa tergesa-gesa membuka notifikasi ponsel.\n\nFokus hari ini adalah menyelesaikan review proyek bulanan dan meluangkan waktu sore untuk jalan kaki 30 menit.',
    date: '2026-10-05',
    time: '07:15',
    mood: 'tenang',
    tags: ['pagi', 'mindfulness', 'kopi'],
    gratitude: 'Udara pagi yang sejuk dan waktu tenang bersama diri sendiri.',
    weather: 'Cerah Berawan',
    updatedAt: Date.now() - 1000 * 60 * 60 * 3,
  },
  {
    id: 'diary-2',
    title: 'Menuntaskan target minggu lalu & refleksi keuangan',
    content:
      'Semua target laporan selesai tepat waktu. Sangat puas dengan ritme kerja minggu ini. Memeriksa kembali catatan keuangan bulan lalu: berhasil menyisihkan 25% untuk dana darurat dan investasi berkala.\n\nPelajaran penting: mencatat pengeluaran kecil harian ternyata sangat efektif mencegah kebocoran anggaran yang tidak disadari.',
    date: '2026-10-04',
    time: '21:00',
    mood: 'produktif',
    tags: ['kerja', 'keuangan', 'refleksi'],
    gratitude: 'Dukungan rekan kerja dan kondisi tubuh yang sehat bugar.',
    weather: 'Hujan Sore',
    updatedAt: Date.now() - 1000 * 60 * 60 * 27,
  },
  {
    id: 'diary-3',
    title: 'Kumpul keluarga santai di akhir pekan',
    content:
      'Menghabiskan hari Minggu bersama keluarga. Makan siang bersama dan berbincang santai tanpa membahas pekerjaan. Hal-hal sederhana seperti ini yang selalu mengisi ulang energi untuk pekan yang baru.',
    date: '2026-10-03',
    time: '19:40',
    mood: 'bersyukur',
    tags: ['keluarga', 'weekend', 'istirahat'],
    gratitude: 'Keluarga yang sehat dan tawa bersama di meja makan.',
    weather: 'Cerah',
    updatedAt: Date.now() - 1000 * 60 * 60 * 50,
  },
];

export const initialTasks: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Siapkan materi presentasi strategi Q4',
    description: 'Rangkum metrik performa Q3 dan susun 5 target prioritas untuk tim.',
    category: 'kerja',
    priority: 'tinggi',
    dueDate: '2026-10-05',
    dueTime: '14:00',
    completed: false,
    alarmEnabled: true,
    alarmTime: '13:45',
    subtasks: [
      { id: 'sub-1', title: 'Unduh data analitik Q3', completed: true },
      { id: 'sub-2', title: 'Buat 5 slide ringkasan eksekutif', completed: false },
      { id: 'sub-3', title: 'Kirim draf ke tim internal', completed: false },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: 'task-2',
    title: 'Belanja bahan makanan mingguan',
    description: 'Beli sayuran segar, telur, susu gandum, dan bumbu dapur di pasar segar.',
    category: 'rumah',
    priority: 'sedang',
    dueDate: '2026-10-05',
    dueTime: '17:30',
    completed: false,
    alarmEnabled: true,
    alarmTime: '17:00',
    subtasks: [
      { id: 'sub-4', title: 'Sayuran hijau & buah', completed: false },
      { id: 'sub-5', title: 'Beras & protein', completed: false },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
  },
  {
    id: 'task-3',
    title: 'Olahraga kardio & peregangan 30 menit',
    description: 'Jogging ringan atau jalan cepat keliling komplek perumahan.',
    category: 'kesehatan',
    priority: 'sedang',
    dueDate: '2026-10-05',
    dueTime: '16:30',
    completed: true,
    completedAt: '2026-10-05T08:30:00Z',
    alarmEnabled: false,
    subtasks: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 20,
  },
  {
    id: 'task-4',
    title: 'Bayar tagihan listrik & internet rumah',
    description: 'Cek tagihan bulanan via m-banking sebelum tanggal 10.',
    category: 'keuangan',
    priority: 'tinggi',
    dueDate: '2026-10-06',
    dueTime: '10:00',
    completed: false,
    alarmEnabled: true,
    alarmTime: '09:30',
    subtasks: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: 'task-5',
    title: 'Membaca 2 bab buku "Atomic Habits"',
    description: 'Fokus pada hukum ke-3: Make it easy.',
    category: 'belajar',
    priority: 'rendah',
    dueDate: '2026-10-05',
    dueTime: '21:30',
    completed: false,
    alarmEnabled: false,
    subtasks: [],
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
  },
];

export const initialFinanceRecords: FinanceRecord[] = [
  // October 2026
  {
    id: 'fin-1',
    type: 'income',
    amount: 14500000,
    category: 'Gaji Pokok',
    date: '2026-10-01',
    notes: 'Gaji bulanan Oktober',
    paymentMethod: 'Transfer Bank',
    createdAt: 1759276800000,
  },
  {
    id: 'fin-2',
    type: 'expense',
    amount: 450000,
    category: 'Tagihan & Utilitas',
    date: '2026-10-01',
    notes: 'Tagihan internet WiFi 100 Mbps',
    paymentMethod: 'E-Wallet',
    createdAt: 1759280400000,
  },
  {
    id: 'fin-3',
    type: 'expense',
    amount: 680000,
    category: 'Belanja Kebutuhan',
    date: '2026-10-02',
    notes: 'Belanja stok sabun, beras, dan perlengkapan mandi bulanan',
    paymentMethod: 'Kartu',
    createdAt: 1759366800000,
  },
  {
    id: 'fin-4',
    type: 'expense',
    amount: 125000,
    category: 'Makanan & Minuman',
    date: '2026-10-02',
    notes: 'Makan siang ayam geprek & es teh dengan rekan kerja',
    paymentMethod: 'E-Wallet',
    createdAt: 1759381200000,
  },
  {
    id: 'fin-5',
    type: 'expense',
    amount: 85000,
    category: 'Transportasi',
    date: '2026-10-03',
    notes: 'Bensin motor pertamax & parkir',
    paymentMethod: 'Tunai',
    createdAt: 1759453200000,
  },
  {
    id: 'fin-6',
    type: 'expense',
    amount: 320000,
    category: 'Hiburan & Hobi',
    date: '2026-10-03',
    notes: 'Nonton bioskop & kopi akhir pekan',
    paymentMethod: 'E-Wallet',
    createdAt: 1759496400000,
  },
  {
    id: 'fin-7',
    type: 'income',
    amount: 2200000,
    category: 'Freelance / Bisnis',
    date: '2026-10-04',
    notes: 'Pembayaran termin 1 desain grafis',
    paymentMethod: 'Transfer Bank',
    createdAt: 1759539600000,
  },
  {
    id: 'fin-8',
    type: 'expense',
    amount: 140000,
    category: 'Makanan & Minuman',
    date: '2026-10-04',
    notes: 'Makan malam soto betawi',
    paymentMethod: 'E-Wallet',
    createdAt: 1759582800000,
  },
  {
    id: 'fin-9',
    type: 'expense',
    amount: 75000,
    category: 'Makanan & Minuman',
    date: '2026-10-05',
    notes: 'Sarapan lontong sayur & kopi',
    paymentMethod: 'Tunai',
    createdAt: 1759626000000,
  },
  {
    id: 'fin-10',
    type: 'expense',
    amount: 2500000,
    category: 'Tabungan & Investasi',
    date: '2026-10-05',
    notes: 'Top-up reksadana pasar uang & saham rutin',
    paymentMethod: 'Transfer Bank',
    createdAt: 1759633200000,
  },
  {
    id: 'fin-11',
    type: 'expense',
    amount: 150000,
    category: 'Kesehatan',
    date: '2026-10-05',
    notes: 'Vitamin C & suplemen daya tahan tubuh',
    paymentMethod: 'E-Wallet',
    createdAt: 1759640400000,
  },
];
